### ISSUE TITLE
Docker Image with HTTPS?

### ISSUE THREAD

**Issue by cc13com** [marlon360/rki-covid-api#101]
Hi,

I was starting the Docker container successful and have access to http://my_IP:8080.

What are the best way to offer this (Docker) server (the api) via https?

Thanks,
cc13

**Comment by marlon360** [comment]
I am using a reverse proxy to resolve a domain name to the docker container and enable SSL with Let's encrypt.

My reverse proxy is also a docker image.
This is the `docker-compose.yml`:
```yml
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - conf:/etc/nginx/conf.d
      - ./proxy_status.conf:/etc/nginx/conf.d/proxy_status.conf:ro
      - vhost:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

volumes:
  conf:
  vhost:
  dhparam:
  certs:
  html:

networks:
  proxy:
    external:
      name: nginx-proxy
```

And this is how I integrate the `rki-server` into the reverse proxy network:
```yml
version: '3.8'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    networks:
      - redis-net
  rki-api:
    image: 'docker.pkg.github.com/marlon360/rki-covid-api/rki-server:v2'
    expose:
      - '3000'
    environment:
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_NAME
      - VIRTUAL_HOST=api.corona-zahlen.org,v2.rki.marlon-lueckert.de
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.corona-zahlen.org,v2.rki.marlon-lueckert.de
      - LETSENCRYPT_EMAIL=m.lueckert@me.com
      - REDIS_URL=redis
    networks:
      - proxy
      - redis-net
    restart: unless-stopped
networks:
  redis-net:
  proxy:
    external:
      name: nginx-proxy
```
