### ISSUE TITLE
Reverse Proxy Docker not longer working

### ISSUE THREAD

**Issue by cc13com** [marlon360/rki-covid-api#329]
Hello @marlon360,

you gave me the instructions in [101](https://github.com/marlon360/rki-covid-api/issues/101) and [206](https://github.com/marlon360/rki-covid-api/issues/206) to run my own docker with https reverse proxy.

All was fine until I saw this week that you now offer the _boosterVaccination_ figures. I tried an update like in #206 described and run `docker-compose pull && docker-compose up -d -V` to update the container. Unfortunately since then I get an 502 gateway error from my nginx. 

I removed all containers, images, networks and started the containers new with the following docker-compose files again.

```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

volumes:
  conf:
  vhost:
  dhparam:
  certs:
  html:

networks:
  proxy:
    external:
      name: nginx-proxy
```

and 

```
version: '3.8'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    networks:
      - redis-net
  rki-api:
    image: 'docker.pkg.github.com/marlon360/rki-covid-api/rki-server:v2'
    container_name: rki-server
    expose:
      - '3000'
    environment:
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_NAME
      - VIRTUAL_HOST=api.my_own_domain.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.my_own_domain.com
      - LETSENCRYPT_EMAIL=my_own_mail_address.com
      - REDIS_URL=redis
    networks:
      - proxy
      - redis-net
    restart: unless-stopped
networks:
  redis-net:
  proxy:
    external:
      name: nginx-proxy
```

Here are the last errors I see in the logs:

nginx_proxy
```
nginx.1     | 2021/11/14 19:06:37 [error] 99#99: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 82.135.86.226, server: api.my_own_domain.com, request: "GET / HTTP/2.0", upstream: "http://172.19.0.3:3000/", host: "api.my_own_domain.com"

nginx.1     | api.my_own_domain.com 82.135.86.226 - - [14/Nov/2021:19:06:37 +0000] "GET / HTTP/2.0" 502 157 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15" "172.19.0.3:3000"
```

rki_server

```
Server running at http://localhost:3000
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
2021-11-14T19:09:10: PM2 log: App name:server id:0 disconnected
2021-11-14T19:09:10: PM2 log: App [server:0] exited with code [0] via signal [SIGINT]
2021-11-14T19:09:10: PM2 log: App [server:0] starting in -cluster mode-
2021-11-14T19:09:10: PM2 log: App [server:0] online
```

Any idea what's wrong?
